### ISSUE TITLE
Add option to generate google managed prometheus kubernetes resources

### ISSUE THREAD

**Issue by alxndr13** [linode-obs/sloth#23]
We had the problem that we were using Google's Managed Prometheus and there is no API like `prometheusrules.monitoring.coreos.com`. 

Instead they're using this CRD:

```
apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: SLO
    app.kubernetes.io/managed-by: sloth
```

Currently we are now transforming the generated YAML, but it would be cool if we could generate it in place. They're also expecting an interval to be set for each group:

```
groups:
  - name: sloth-slo-sli-recordings-api-success-rate
    interval: 30s
```

So the thing is they don't differ that much, but it would be nice if we could generate it like with an additional option.
